#include "settings.h"

// Initialize GPIOs for ILI9341 + SERCOM SPI interface
void GPIO_init() {

    /* 
     * PA05 -> SCK  SPI OUT (SERCOM0)
     * PA06 -> CS  ILI9341 SPI OUT (SERCOM0)
     * PA07 -> MOSI SPI OUT(SERCOM0)
     * PA08 -> RESET OUT (ILI9341) SPI (SERCOM0)
     * PA09 -> DC OUT (Data/Command) SPI (SERCOM0)
     * PA10 -> XPT4026 CS SPI OUT (SERCOM0)
     * 
     * PA12 -> RS485 TX OUT (SERCOM2) PAD0
     * PA14 -> RS485 TE OUT (SERCOM2) PAD2
     * 
     * PA16 -> SERVER data sending indication LED
     * 
     * PA17 -> A767E USART TX OUT (SERCOM3)
     * PA19 -> A7672E MODULE Enable
     * 
     * PA20 -> LCD backlight enable
     * 
     * PA21 -> SENSORS RS485 TXLED
     * PA22 -> SENSORS RS485 RXLED
     * PA23 -> SENSORS RS485 TX (SERCOM5) PAD0
     * PA24 -> SENSORS RS485 TE (SERCOM5) PAD2    
     */
    PORT_REGS->GROUP[0].PORT_DIRSET = PORT_PA05 | PORT_PA06 | PORT_PA07 | PORT_PA08 | PORT_PA09 | PORT_PA10 | PORT_PA12 | PORT_PA14 | PORT_PA16  | PORT_PA17 | PORT_PA19 | PORT_PA20 | PORT_PA21 | PORT_PA22 | PORT_PA23 | PORT_PA24;
    
    
    /*
     * PB10 -> TOWERS RS485 TXLED
     * PB11 -> TOWERS RS485 RXLED
     */
    PORT_REGS->GROUP[1].PORT_DIRSET = PORT_PB10 | PORT_PB11;
    
     /* 
     * PA04 -> MISO SPI IN (SERCOM0)
     * PA15 -> RS485 RX IN (SERCOM2) PAD3 
     * PA18 -> A767E USART RX (IN SERCOM3)
     * PA25 -> SENSORS RS485 RX (SERCOM5) 
     */
    PORT_REGS->GROUP[0].PORT_DIRCLR =   PORT_PA04 | PORT_PA15 | PORT_PA18 | PORT_PA25;
    
    PORT_REGS->GROUP[0].PORT_PINCFG[4] = PORT_PINCFG_PMUXEN_Msk; // PA04 SERCOM0 SPI PAD0 MISO
    PORT_REGS->GROUP[0].PORT_PINCFG[5] = PORT_PINCFG_PMUXEN_Msk; // PA05 SERCOM0 SPI PAD1 SCK
    PORT_REGS->GROUP[0].PORT_PINCFG[7] = PORT_PINCFG_PMUXEN_Msk; // PA07 SERCOM0 SPI PAD3 MOSI
    
    PORT_REGS->GROUP[0].PORT_PINCFG[12] = PORT_PINCFG_PMUXEN_Msk; // PA12 SERCOM2 RS485 PAD0 TX
    PORT_REGS->GROUP[0].PORT_PINCFG[14] = PORT_PINCFG_PMUXEN_Msk; // PA14 SERCOM2 RS485 PAD2 TE 
    PORT_REGS->GROUP[0].PORT_PINCFG[15] = PORT_PINCFG_PMUXEN_Msk; // PA15 SERCOM2 RS485 PAD3 RX
    
    PORT_REGS->GROUP[0].PORT_PINCFG[16] = PORT_PINCFG_DRVSTR_Msk; // PA16 Server transsmit led set as high
    PORT_REGS->GROUP[0].PORT_OUTSET = PORT_PA16;//// PA16 Server transsmit led set as high
    
    PORT_REGS->GROUP[0].PORT_PINCFG[17] = PORT_PINCFG_PMUXEN_Msk; // PA17 SERCOM3 PAD0 USART TX    
    PORT_REGS->GROUP[0].PORT_PINCFG[18] = PORT_PINCFG_PMUXEN_Msk; // PA18 SERCOM3 PAD2 USART RX
    
    PORT_REGS->GROUP[0].PORT_PINCFG[23] = PORT_PINCFG_PMUXEN_Msk; // PA23 SERCOM5 RS485 PAD0 TX
    PORT_REGS->GROUP[0].PORT_PINCFG[24] = PORT_PINCFG_PMUXEN_Msk; // PA24 SERCOM5 RS485 PAD2 TE 
    PORT_REGS->GROUP[0].PORT_PINCFG[25] = PORT_PINCFG_PMUXEN_Msk; // PA25 SERCOM5 RS485 PAD3 RX


    /* --- Configure PMUX (peripheral multiplexing) ---
     * PMUX pairs pins as even+odd: 0+1, 2+3, 4+5, ...
     * Function D = SERCOM (SPI in this case)
     */
    PORT_REGS->GROUP[0].PORT_PMUX[4 >> 1] = PORT_PMUX_PMUXE_D | PORT_PMUX_PMUXO_D; // PA04 even, PA05 (odd) SERCOM0 function D
    PORT_REGS->GROUP[0].PORT_PMUX[7 >> 1] = PORT_PMUX_PMUXO_D; // PA07 odd SERCOM0 function D
    
    PORT_REGS->GROUP[0].PORT_PMUX[12 >> 1] = PORT_PMUX_PMUXE_C; // PA12 use only as  SERCOM2 function C- RS485 TX
    PORT_REGS->GROUP[0].PORT_PMUX[14 >> 1] = PORT_PMUX_PMUXE_C | PORT_PMUX_PMUXO_C; // PA14 and PA15 as RS485 TE and RX SERCOM2   
    
    PORT_REGS->GROUP[0].PORT_PMUX[17 >> 1] =  PORT_PMUX_PMUXO_D; //only odd pin (17) uses d function (sercom 3) USART A767E TX
    PORT_REGS->GROUP[0].PORT_PMUX[18 >> 1] =  PORT_PMUX_PMUXE_D; //only odd pin (18) uses d function (sercom 3) USART A767E
    
    PORT_REGS->GROUP[0].PORT_PMUX[23 >> 1] = PORT_PMUX_PMUXO_D; // PA23 use only as  SERCOM5 function D- RS485 TX
    PORT_REGS->GROUP[0].PORT_PMUX[24 >> 1] = PORT_PMUX_PMUXE_D | PORT_PMUX_PMUXO_D; // PA24 and PA25 as RS485 TE and RX SERCOM5
    
        
}

